version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - default

  api:
    build: 
      context: .
    container_name: healthbrain_api
    ports:
      - '8787:8787'
    restart: always
    env_file:
      - ./.env
    networks:
      - default
    depends_on:
      - postgres
    command: app/api.py

  dashboard:
    build: 
      context: .
    container_name: healthbrain_dashboard
    ports:
      - '8050:8050'
    restart: always
    env_file:
      - ./.env
    networks:
      - default
    depends_on:
      - postgres
    command: app/dashboard.py

volumes:
  postgres-db:

networks:
  default:
    name: healthbrain
    driver: bridge
