"""unique constraint on date and user id in weights

Revision ID: 67268468b065
Revises: 76940dc0cd6f
Create Date: 2023-02-06 00:15:57.720881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67268468b065'
down_revision = '76940dc0cd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'weights', ['user_id', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weights', type_='unique')
    # ### end Alembic commands ###
